### ISSUE TITLE
Bump expo to latest version

### ISSUE THREAD

**Issue by kacgrzes** [kacgrzes/expo-typescript-template#22]
@MSzalowski @MateuszRostkowski we could bump expo to the latest version. What do you think?

**Comment by MateuszRostkowski** [comment]
It's good idea 🤩

@michalbaumruck alredy strated upgrading his project to expo 46. We could ask him for some tips

**Comment by kacgrzes** [comment]
I've just added Michał to the repository

**Comment by MateuszRostkowski** [comment]
Done in [MR#25](https://github.com/kacgrzes/expo-typescript-template/pull/25) 🎉
